version: "3.2"

services:
  app:
    image: maven:3.5.0-jdk-8-alpine
    volumes:
      - "$HOME/.m2:/root/.m2"
      - "$PWD:/usr/src/app"
    working_dir: /usr/src/app
    entrypoint: "sh"
    environment:
      ELASTICMQ_HOST: elasticmq
      ZK_HOST: zookeeper

  elasticmq:
    image: fingershock/elasticmq:0.13.2
    ports:
      - "9324:9324"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.8.2.2-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
